apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: default
  labels:
    app: mcp-server
spec:
  type: ClusterIP
  selector:
    app: mcp-server
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
