apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-deployment-statefulset
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  serviceName: nginx-statefulset-servicename
  selector:
    matchLabels:
      app: nginx
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

# k apply -f ./k8s/nginx-statefulset
