name: Check ENV

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#    - name: Check ip
#      run: curl -X GET 180.229.80.50:8000/api/check-ip

    - name: Check runner
      run: whoami

    - name: Check pwd
      run: pwd

    - name: Check ifconfig
      run: ifconfig

    - name: Check ENV
      run: env

    - name: Check pocesses
      run: ps -ef
