name: Scheduled Jobs

on:
  push:
    branches: [ main ]
#  schedule:
#    - cron: '0 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"

      - name: repository checkout
        uses: actions/checkout@v2
        with:
          repository: $GITHUB_REPOSITORY
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          path: infra-study

      - name: Add date and push
        run: |
          cd infra-study
          date >> date.txt
          git add .
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
#          git commit -am "Inject Date"
#          git push

